spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        generate_statistics: true

logging:
  level:
    com.xuyi.blog: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 开发环境允许跨域
cors:
  allowed-origins: 
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:8080"
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# 阿里云OSS配置
aliyun:
  oss:
    endpoint: ${ALIYUN_OSS_ENDPOINT:https://oss-cn-beijing.aliyuncs.com}
    access-key-id: ${ALIYUN_OSS_ACCESS_KEY_ID:your_access_key_id}
    access-key-secret: ${ALIYUN_OSS_ACCESS_KEY_SECRET:your_access_key_secret}
    bucket-name: ${ALIYUN_OSS_BUCKET_NAME:your_bucket_name}
    base-url: ${ALIYUN_OSS_BASE_URL:https://your-bucket.oss-cn-beijing.aliyuncs.com/}
